# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://Tantalus13A98B5F.github.io/"
title = "Tantalus!"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true
googleAnalytics = "UA-155994167-1"
paginate = 9

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

defaultContentLanguage = "en"
[languages.en]
  languageCode = "en"

[author]
  name = "Tantalus"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[params]
  since = "2020"
  baidu_analytics = "aeaa2384b12fe093fad3519714e7034b"
  photoswipe = true  # see https://github.com/dimsemenov/PhotoSwipe
